# -*- coding: utf-8 -*-
"""Yahoo Finance Scraping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15dybOF3IvRMXj0vWgXsJee5cCSHi_4wv

IMPORTING REQUIRED MODULES
"""

import re
import csv
import json
from io import StringIO
from bs4 import BeautifulSoup
import requests
import pandas as pd

"""OPEN A OUTPUT CSV FILE"""

outputfile = open('financialstats.csv', 'w', newline='')
outputWriter = csv.writer(outputfile)
outputWriter.writerow(["Name", "CurrentRatio", "DebToEQRatio", "Return On Assets", "Return on Earning", "Net Profit","RevenueGrowth(yoy)"])

"""REQUESTING AND WRITING DATA TO CSV FILE"""

url_stats = "https://in.finance.yahoo.com/quote/{}/key-statistics?p={}"
stocks = ['TITAN.NS','BHARTIARTL.NS','TECHM.NS','TINPLATE.NS','TITAN.NS','TORNTPHARM','HDFCLIFE.NS','ULTRACEMCO.NS','ICICIBANK.NS','SHREECEM.NS','BAJFINANCE.NS','CIPLA.NS','BAJAJ-AUTO.NS','KOTAKBANK.NS','TATACONSUM.NS','TECHM.NS','TCS.NS','MARUTI.NS','NTPC.NS','BRITANNIA.NS','WIPRO.NS','ONGC.NS','LT.NS','INDUSINDBK.NS','NESTLEIND.NS','GRASIM.NS','TATASTEEL.NS','HINDALCO.NS','COALINDIA.NS','3IINFOTECH.BO','HFCL.NS','TRIDENT.NS','PNB.NS','JPPOWER.NS','BHEL.NS','IDEA.NS','YESBANK.NS','BAJAJHIND.NS','BANKBARODA.NS','SBIN.NS','SAIL.NS','RENUKA.NS','ITC.NS','UPL.NS','RPOWER.NS','TATAMOTORS.NS','TATAPOWER.NS','TATAMTRDVR-BL.NS','FORTIS-BL.NS','NATIONALUM.NS','LICHFIN.NS','GLENMARK.NS','BIOCON.NS','RELIANCE.NS','ALKYLAMINE.NS','MARKSANS.NS','IBULHSGFIN.NS','SAHYADRI.NS','MRF.NS','MARICO.NS','TATACONSUM.NS','BAJFINANCE.NS','GICHSGFIN.NS','UNIONBANK.NS','BANKBARODA.NS','RBLBANK.NS','FEDERALBNK.NS','BANDHANBNK.NS','AXISBANK.NS','ICICIBANK.NS','KOTAKBANK.NS','HDFCBANK.NS','ZEEL.NS','APOLLO.NS','BALAJITELE.NS','BANKINDIA.NS','BFUTILITIE.NS','BHEL.NS','BPCL.NS','CADILAHC.NS','CANBK.NS','COFORGE.NS','DAAWAT.NS','DELTACORP.NS','DIVISLAB.NS','DLF.NS','DLINKINDIA.NS','EIHOTEL.NS','ESCORT.NS','GILLETTE.NS','GLOBUSSPR.NS','GNA.NS','GSFC.NS','GUJGASLTD.NS','HEROMOTOCO.NS','IGL.NS','IOC.NS','IOLCP.NS','IRCTC.NS','JAICORPLTD.NS','LT.NS','LUPIN.NS','NTPC.NS','PVR.NS','SBILIFE.NS','SUNTV.NS']
cr = []
deq = []
roass = []
roeq = []
netprofit = []
revenue = []

for stock in stocks:
    try :
        response = requests.get(url_stats.format(stock, stock) )
        soup = BeautifulSoup(response.text, 'html.parser')
        soup.text[:200]
        pattern = re.compile(r'\s--\sData\s--\s')
        script_data = soup.find('script', text=pattern).contents[0]
        script_data[:500]
        start = script_data.find("context")-2
        json_data = json.loads(script_data[start:-12])
    #json_data['context']['dispatcher']['stores']['QuoteSummaryStore'].keys()
        current_ratio = json_data['context']['dispatcher']['stores']['QuoteSummaryStore']['financialData']['currentRatio'].get('fmt', 0)
        debt_to_eqr = json_data['context']['dispatcher']['stores']['QuoteSummaryStore']['financialData']['debtToEquity'].get('fmt', 0)
        ROA = json_data['context']['dispatcher']['stores']['QuoteSummaryStore']['financialData']['returnOnAssets'].get('fmt', 0)
        ROE = json_data['context']['dispatcher']['stores']['QuoteSummaryStore']['financialData']['returnOnEquity'].get('fmt', 0)
        net_profit_margin = json_data['context']['dispatcher']['stores']['QuoteSummaryStore']['financialData']['profitMargins'].get('fmt', 0)
        revenueGrowth = json_data['context']['dispatcher']['stores']['QuoteSummaryStore']['financialData']['revenueGrowth'].get('fmt', 0)
        try : 
            outputWriter.writerow([stock, current_ratio, debt_to_eqr,ROA, ROE,net_profit_margin, revenueGrowth] )
        except KeyError:
            continue
    except KeyError:
        continue
#pd.DataFrame({"Name": s, "CurrentRatio": cr, "DebToEQRatio": deq, "Return On Assets": roass, "Return on Earning": roeq, "Net Profit": netprofit,"RevenueGrowth(yoy)": revenue})

"""CLOSE THE CSV FILE"""

outputfile.close()

